# Generated by Django 4.1.7 on 2023-04-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование товара')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Фото товара')),
                ('description', models.CharField(blank=True, max_length=256, verbose_name='Описание товара')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='Цвет товара')),
                ('price', models.PositiveIntegerField(verbose_name='Цена товара')),
                ('link_to_shop', models.CharField(max_length=256, verbose_name='Ссылка на магазин')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('-created_at',),
            },
        ),
    ]
