# Generated by Django 4.1.7 on 2023-04-24 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=3000, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.ForeignKey(help_text='Группа к которой принадлежит товар', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.group', verbose_name='Группа'),
        ),
    ]
